INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (7, 'Erlang', null, null, null, 2, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (8, 'Go', null, null, null, 2, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (9, 'Java', null, null, null, 2, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (10, 'LISP', null, null, null, 2, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (11, 'MATLAB', null, null, null, 2, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (12, 'Objective C', null, null, null, 2, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (13, 'R', null, null, null, 2, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (14, 'Scala', null, null, null, 2, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (15, 'Swift', null, null, null, 2, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (18, 'Backbone', null, null, null, 3, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (19, 'Bootstrap', null, null, null, 3, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (20, 'CSS', null, null, null, 3, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (21, 'Electron', null, null, null, 3, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (22, 'EmberJS', null, null, null, 3, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (28, 'Web Sockets', null, null, null, 3, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (29, 'Lua', null, null, null, 4, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (30, 'Perl', null, null, null, 4, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (31, 'Python', null, null, null, 4, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (32, 'Ruby', null, null, null, 4, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (33, 'Apache Flume', null, null, null, 5, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (34, 'Apache Kafka', null, null, null, 5, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (35, 'Apache Pig', null, null, null, 5, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (38, 'CouchDB', null, null, null, 5, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (39, 'Hadoop', null, null, null, 5, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (40, 'DB2', null, null, null, 6, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (41, 'DocumentDB', null, null, null, 6, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (42, 'H2', null, null, null, 6, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (43, 'MariaDB', null, null, null, 6, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (44, 'Memcached', null, null, null, 6, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (45, 'MongoDb', null, null, null, 6, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (47, 'Neo4j', null, null, null, 6, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (48, 'OrientDB', null, null, null, 6, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (49, 'PostgreSQL', null, null, null, 6, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (50, 'Redis', null, null, null, 6, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (51, 'SQL', null, null, null, 6, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (52, 'SQLite', null, null, null, 6, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (54, 'AWS', null, null, null, 7, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (55, 'Azure', null, null, null, 7, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (56, 'Linux', null, null, null, 7, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (57, 'Ubuntu', null, null, null, 7, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (58, 'Red Hat', null, null, null, 7, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (59, 'CentOS', null, null, null, 7, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (60, 'Android', null, null, null, 8, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (61, 'Cordova', null, null, null, 8, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (62, 'Ionic', null, null, null, 8, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (63, 'iOS', null, null, null, 8, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (65, 'Native Script', null, null, null, 8, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (66, 'Xamarin', null, null, null, 8, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (67, 'ASP.NET', null, null, null, 9, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (68, 'NodeJS', null, null, null, 9, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (70, 'Ruby On Rails', null, null, null, 9, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (71, 'Laravel', null, null, null, 9, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (72, 'Symphony', null, null, null, 9, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (73, 'CodeIgniter', null, null, null, 9, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (74, 'ExpressJS', null, null, null, 9, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (53, 'C Sharp', null, null, null, 2, '1');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (1, 'Assembly', null, null, 'asm', 2, '1');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (5, 'Cobol', null, 'Cobol', 'Cobol', 2, '1');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (16, 'Angular', null, 'Angular', 'angularjs', 3, '1');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (36, 'Apache Solr', null, 'Solr', 'Solr', 5, '1');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (17, 'Aurelia', null, 'Aurelia', 'aureliajs', 3, '1');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (2, 'C', null, null, 'C_Programming', 2, '1');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (3, 'C++', null, null, 'cpp', 2, '1');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (37, 'Cassandra', null, null, null, 5, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (4, 'Clojure', null, 'Clojure', 'Clojure', 2, '1');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (6, 'Elixir', null, 'Elixir', 'Elixir', 2, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (23, 'ES6', null, 'ES6', null, 3, '1');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (76, 'Foundation', null, null, 'foundation', 3, '1');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (24, 'HTML', null, 'HTML', 'HTML', 3, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (25, 'JavaScript', null, 'javascript', 'javascript', 3, '1');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (26, 'jQuery', null, 'jQuery', 'jQuery', 3, '1');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (77, 'KoaJS', null, null, 'koajs', 9, '1');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (46, 'MySQL', null, 'MySQL', 'MySQL', 6, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (69, 'PHP', null, 'PHP', 'PHP', 9, '1');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (27, 'ReactJS', null, 'react', 'reactjs', 3, '1');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (64, 'React Native', null, null, 'reactnative', 8, '1');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (75, 'WebRTC', null, 'WebRTC', 'WebRTC', 3, '1');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active") VALUES (78, 'Phalcon', null, null, 'phalcon', 9, '1');