INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (9, 'Java', null, null, null, 2, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (10, 'LISP', null, null, null, 2, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (11, 'MATLAB', null, null, null, 2, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (12, 'Objective C', null, null, null, 2, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (13, 'R', null, null, null, 2, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (14, 'Scala', null, null, null, 2, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (15, 'Swift', null, null, null, 2, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (3, 'C++', null, null, 'cpp', 2, '1', 'cplusplus', null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (18, 'Backbone', null, null, null, 3, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (19, 'Bootstrap', null, null, null, 3, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (20, 'CSS', null, null, null, 3, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (21, 'Electron', null, null, null, 3, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (22, 'EmberJS', null, null, null, 3, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (28, 'Web Sockets', null, null, null, 3, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (29, 'Lua', null, null, null, 4, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (30, 'Perl', null, null, null, 4, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (31, 'Python', null, null, null, 4, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (32, 'Ruby', null, null, null, 4, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (38, 'CouchDB', null, null, null, 5, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (39, 'Hadoop', null, null, null, 5, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (40, 'DB2', null, null, null, 6, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (41, 'DocumentDB', null, null, null, 6, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (42, 'H2', null, null, null, 6, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (43, 'MariaDB', null, null, null, 6, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (44, 'Memcached', null, null, null, 6, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (45, 'MongoDb', null, null, null, 6, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (47, 'Neo4j', null, null, null, 6, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (48, 'OrientDB', null, null, null, 6, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (49, 'PostgreSQL', null, null, null, 6, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (50, 'Redis', null, null, null, 6, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (51, 'SQL', null, null, null, 6, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (52, 'SQLite', null, null, null, 6, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (54, 'AWS', null, null, null, 7, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (55, 'Azure', null, null, null, 7, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (56, 'Linux', null, null, null, 7, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (57, 'Ubuntu', null, null, null, 7, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (58, 'Red Hat', null, null, null, 7, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (59, 'CentOS', null, null, null, 7, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (61, 'Cordova', null, null, null, 8, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (62, 'Ionic', null, null, null, 8, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (63, 'iOS', null, null, null, 8, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (65, 'Native Script', null, null, null, 8, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (66, 'Xamarin', null, null, null, 8, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (67, 'ASP.NET', null, null, null, 9, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (68, 'NodeJS', null, null, null, 9, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (70, 'Ruby On Rails', null, null, null, 9, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (71, 'Laravel', null, null, null, 9, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (72, 'Symphony', null, null, null, 9, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (73, 'CodeIgniter', null, null, null, 9, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (74, 'ExpressJS', null, null, null, 9, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (60, 'Android', null, 'Android', 'androiddev', 8, '1', 'Android', 'Android');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (16, 'Angular', null, 'Angular', 'angularjs', 3, '1', 'angular2', 'angular2');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (33, 'Apache Flume', null, 'Flume', null, 5, '1', null, 'apache-flume');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (36, 'Apache Solr', null, 'Solr', 'Solr', 5, '1', 'solr', 'apache-solr');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (17, 'Aurelia', null, 'Aurelia', 'aureliajs', 3, '1', 'aurelia', 'aurelia');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (4, 'Clojure', null, 'Clojure', 'Clojure', 2, '1', 'clojure', 'clojure');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (53, 'C Sharp', null, null, null, 2, '1', 'c_sharp', 'c-sharp');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (7, 'Erlang', null, 'erlang', 'erlang', 2, '1', 'erlang', 'erlang');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (25, 'JavaScript', null, 'javascript', 'javascript', 3, '1', 'javascript', 'javascript');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (37, 'Cassandra', null, null, null, 5, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (6, 'Elixir', null, 'Elixir', 'Elixir', 2, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (24, 'HTML', null, 'HTML', 'HTML', 3, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (46, 'MySQL', null, 'MySQL', 'MySQL', 6, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (27, 'ReactJS', null, 'react', 'reactjs', 3, '1', 'reactjs', 'reactjs');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (8, 'Go', null, 'Android', 'androiddev', 2, null, null, null);
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (64, 'React Native', null, null, 'reactnative', 8, '1', null, 'react-native');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (75, 'WebRTC', null, 'WebRTC', 'WebRTC', 3, '1', 'webrtc', 'webrtc');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (1, 'Assembly', null, null, 'asm', 2, '1', null, 'assembly');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (2, 'C', null, null, 'C_Programming', 2, '1', null, 'c');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (34, 'Apache Kafka', null, null, 'apachekafka', 5, '1', 'apache_kafka', 'apache-kafka');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (23, 'ES6', null, 'ES6', null, 3, '1', null, 'es6');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (76, 'Foundation', null, null, 'foundation', 3, '1', null, 'foundation');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (5, 'COBOL', null, 'Cobol', 'Cobol', 2, '1', 'cobol', 'cobol');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (77, 'KoaJS', null, null, 'koajs', 9, '1', null, 'koajs');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (26, 'jQuery', null, 'jQuery', 'jQuery', 3, '1', 'jquery', 'jquery');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (78, 'Phalcon', null, null, 'phalcon', 9, '1', null, 'phalcon');
INSERT INTO "CINS"."SubTopics" ("Id", "Name", "SearchTerm", "InfoWorld", "Reddit", "MainTopicsId", "Active", "Infoq", "Medium") VALUES (69, 'PHP', null, 'PHP', 'PHP', 9, '1', 'php', 'php');